//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gameosoftv2.PlayService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlayService.IPlayService")]
    public interface IPlayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayService/InsertUserGameRecord", ReplyAction="http://tempuri.org/IPlayService/InsertUserGameRecordResponse")]
        void InsertUserGameRecord(int GameId, string UserId, string HoursPlayed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayService/InsertUserGameRecord", ReplyAction="http://tempuri.org/IPlayService/InsertUserGameRecordResponse")]
        System.Threading.Tasks.Task InsertUserGameRecordAsync(int GameId, string UserId, string HoursPlayed);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayServiceChannel : Gameosoftv2.PlayService.IPlayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayServiceClient : System.ServiceModel.ClientBase<Gameosoftv2.PlayService.IPlayService>, Gameosoftv2.PlayService.IPlayService {
        
        public PlayServiceClient() {
        }
        
        public PlayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertUserGameRecord(int GameId, string UserId, string HoursPlayed) {
            base.Channel.InsertUserGameRecord(GameId, UserId, HoursPlayed);
        }
        
        public System.Threading.Tasks.Task InsertUserGameRecordAsync(int GameId, string UserId, string HoursPlayed) {
            return base.Channel.InsertUserGameRecordAsync(GameId, UserId, HoursPlayed);
        }
    }
}
